### ISSUE TITLE
Uncaught Error Vue.js

### ISSUE THREAD

**Issue by juanbrujo** [IzumiSy/chat-frontend#2]
I'm having this error running `$ gulp`:

'Uncaught Error: Must start vue-router with a component, not a Vue instance.'

nothing happens in the interface.

**Comment by IzumiSy** [comment]
Can you let me know what line that error occured?

**Comment by IzumiSy** [comment]
Hi. It seems a bug caused by version-up of vue-router. I created PR (https://github.com/IzumiSy/chat-frontend/pull/3) to fix it. Check it out.

**Comment by juanbrujo** [comment]
yep passed that error with #3. 

now a new one: `Uncaught ReferenceError: app is not defined` 
app.js line 824: `routings.start(app, "body");`

**Comment by IzumiSy** [comment]
@juanbrujo Hi. I pushed some more changes to #3 as a quick fix. Could you try that out?

**Comment by juanbrujo** [comment]
👍now it opens the chat interface. but...

![screen shot 2016-02-12 at 14 53 27](https://cloud.githubusercontent.com/assets/362186/13015568/8f71cc5e-d198-11e5-8fa6-cd3eb56585e5.png)

**Comment by IzumiSy** [comment]
@juanbrujo Hi, sorry to make you wait for a while. I pushed a change into master, so I guess you can get it work now.
